"""empty message

Revision ID: 40d54584d8a9
Revises: 1069d37ec68a
Create Date: 2020-04-20 20:54:57.684067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d54584d8a9'
down_revision = '1069d37ec68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('name_product', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('id_restaurant', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_restaurant'], ['restaurantusers.id'], ),
    sa.PrimaryKeyConstraint('id_product'),
    sa.UniqueConstraint('description')
    )
    op.create_table('ingredient',
    sa.Column('id_ingredinet', sa.Integer(), nullable=False),
    sa.Column('name_ingredinet', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_product'], ['product.id_product'], ),
    sa.PrimaryKeyConstraint('id_ingredinet')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient')
    op.drop_table('product')
    # ### end Alembic commands ###
