"""empty message

Revision ID: dd9dbacc56b8
Revises: 59cd063594a0
Create Date: 2020-05-03 00:03:47.629229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9dbacc56b8'
down_revision = '59cd063594a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'order_number')
    # ### end Alembic commands ###
